// <auto-generated/>
#pragma warning disable CS0618
using KbStoreApiClient.Inventory.Item.Decrease;
using KbStoreApiClient.Inventory.Item.Description;
using KbStoreApiClient.Inventory.Item.Hold;
using KbStoreApiClient.Inventory.Item.Increase;
using KbStoreApiClient.Inventory.Item.Release;
using KbStoreApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KbStoreApiClient.Inventory.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \inventory\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InventoryItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The decrease property</summary>
        public global::KbStoreApiClient.Inventory.Item.Decrease.DecreaseRequestBuilder Decrease
        {
            get => new global::KbStoreApiClient.Inventory.Item.Decrease.DecreaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The description property</summary>
        public global::KbStoreApiClient.Inventory.Item.Description.DescriptionRequestBuilder Description
        {
            get => new global::KbStoreApiClient.Inventory.Item.Description.DescriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hold property</summary>
        public global::KbStoreApiClient.Inventory.Item.Hold.HoldRequestBuilder Hold
        {
            get => new global::KbStoreApiClient.Inventory.Item.Hold.HoldRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The increase property</summary>
        public global::KbStoreApiClient.Inventory.Item.Increase.IncreaseRequestBuilder Increase
        {
            get => new global::KbStoreApiClient.Inventory.Item.Increase.IncreaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The release property</summary>
        public global::KbStoreApiClient.Inventory.Item.Release.ReleaseRequestBuilder Release
        {
            get => new global::KbStoreApiClient.Inventory.Item.Release.ReleaseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KbStoreApiClient.Inventory.Item.InventoryItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InventoryItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/inventory/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KbStoreApiClient.Inventory.Item.InventoryItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InventoryItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/inventory/{id}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::KbStoreApiClient.Models.InventoryModel"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::KbStoreApiClient.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::KbStoreApiClient.Models.ProblemDetails">When receiving a 409 status code</exception>
        /// <exception cref="global::KbStoreApiClient.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KbStoreApiClient.Models.InventoryModel?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KbStoreApiClient.Models.InventoryModel> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::KbStoreApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "409", global::KbStoreApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::KbStoreApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::KbStoreApiClient.Models.InventoryModel>(requestInfo, global::KbStoreApiClient.Models.InventoryModel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::KbStoreApiClient.Models.InventoryModel"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::KbStoreApiClient.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::KbStoreApiClient.Models.ProblemDetails">When receiving a 409 status code</exception>
        /// <exception cref="global::KbStoreApiClient.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KbStoreApiClient.Models.InventoryModel?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KbStoreApiClient.Models.InventoryModel> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::KbStoreApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "409", global::KbStoreApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::KbStoreApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::KbStoreApiClient.Models.InventoryModel>(requestInfo, global::KbStoreApiClient.Models.InventoryModel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::KbStoreApiClient.Inventory.Item.InventoryItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KbStoreApiClient.Inventory.Item.InventoryItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KbStoreApiClient.Inventory.Item.InventoryItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InventoryItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InventoryItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
