// <auto-generated/>
#pragma warning disable CS0618
using KbStoreApiClient.Inventory.Item;
using KbStoreApiClient.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KbStoreApiClient.Inventory
{
    /// <summary>
    /// Builds and executes requests for operations under \inventory
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InventoryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KbStoreApiClient.inventory.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::KbStoreApiClient.Inventory.Item.InventoryItemRequestBuilder"/></returns>
        public global::KbStoreApiClient.Inventory.Item.InventoryItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::KbStoreApiClient.Inventory.Item.InventoryItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the KbStoreApiClient.inventory.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::KbStoreApiClient.Inventory.Item.InventoryItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::KbStoreApiClient.Inventory.Item.InventoryItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::KbStoreApiClient.Inventory.Item.InventoryItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KbStoreApiClient.Inventory.InventoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InventoryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/inventory?Page={Page}&Size={Size}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KbStoreApiClient.Inventory.InventoryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InventoryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/inventory?Page={Page}&Size={Size}", rawUrl)
        {
        }
        /// <returns>A <see cref="global::KbStoreApiClient.Models.PaginatedResponseOfInventoryModel"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::KbStoreApiClient.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::KbStoreApiClient.Models.ProblemDetails">When receiving a 409 status code</exception>
        /// <exception cref="global::KbStoreApiClient.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KbStoreApiClient.Models.PaginatedResponseOfInventoryModel?> GetAsync(Action<RequestConfiguration<global::KbStoreApiClient.Inventory.InventoryRequestBuilder.InventoryRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KbStoreApiClient.Models.PaginatedResponseOfInventoryModel> GetAsync(Action<RequestConfiguration<global::KbStoreApiClient.Inventory.InventoryRequestBuilder.InventoryRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::KbStoreApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "409", global::KbStoreApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::KbStoreApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::KbStoreApiClient.Models.PaginatedResponseOfInventoryModel>(requestInfo, global::KbStoreApiClient.Models.PaginatedResponseOfInventoryModel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="global::KbStoreApiClient.Models.InventoryModel"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::KbStoreApiClient.Models.ProblemDetails">When receiving a 400 status code</exception>
        /// <exception cref="global::KbStoreApiClient.Models.ProblemDetails">When receiving a 409 status code</exception>
        /// <exception cref="global::KbStoreApiClient.Models.ProblemDetails">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KbStoreApiClient.Models.InventoryModel?> PostAsync(global::KbStoreApiClient.Models.CreateInventoryPayload body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KbStoreApiClient.Models.InventoryModel> PostAsync(global::KbStoreApiClient.Models.CreateInventoryPayload body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::KbStoreApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "409", global::KbStoreApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
                { "500", global::KbStoreApiClient.Models.ProblemDetails.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::KbStoreApiClient.Models.InventoryModel>(requestInfo, global::KbStoreApiClient.Models.InventoryModel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KbStoreApiClient.Inventory.InventoryRequestBuilder.InventoryRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KbStoreApiClient.Inventory.InventoryRequestBuilder.InventoryRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::KbStoreApiClient.Models.CreateInventoryPayload body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::KbStoreApiClient.Models.CreateInventoryPayload body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/inventory", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::KbStoreApiClient.Inventory.InventoryRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KbStoreApiClient.Inventory.InventoryRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KbStoreApiClient.Inventory.InventoryRequestBuilder(rawUrl, RequestAdapter);
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class InventoryRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            public int? Page { get; set; }
            public int? Size { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InventoryRequestBuilderGetRequestConfiguration : RequestConfiguration<global::KbStoreApiClient.Inventory.InventoryRequestBuilder.InventoryRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InventoryRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
