// <auto-generated/>
#pragma warning disable CS0618
using KbStoreApiClient.Inventory.Item.Increase.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KbStoreApiClient.Inventory.Item.Increase
{
    /// <summary>
    /// Builds and executes requests for operations under \inventory\{id}\increase
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IncreaseRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KbStoreApiClient.inventory.item.increase.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::KbStoreApiClient.Inventory.Item.Increase.Item.WithQuantityItemRequestBuilder"/></returns>
        public global::KbStoreApiClient.Inventory.Item.Increase.Item.WithQuantityItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("quantity", position);
                return new global::KbStoreApiClient.Inventory.Item.Increase.Item.WithQuantityItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the KbStoreApiClient.inventory.item.increase.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::KbStoreApiClient.Inventory.Item.Increase.Item.WithQuantityItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::KbStoreApiClient.Inventory.Item.Increase.Item.WithQuantityItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("quantity", position);
                return new global::KbStoreApiClient.Inventory.Item.Increase.Item.WithQuantityItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KbStoreApiClient.Inventory.Item.Increase.IncreaseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IncreaseRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/inventory/{id}/increase", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KbStoreApiClient.Inventory.Item.Increase.IncreaseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IncreaseRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/inventory/{id}/increase", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
