<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <PropertyGroup>
    <IsTestingPlatformApplication>false</IsTestingPlatformApplication>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KbStore.Catalog.Abstractions\KbStore.Catalog.Abstractions.csproj" />
    <ProjectReference Include="..\KbStore.Catalog.Services\KbStore.Catalog.Services.csproj" />
    <ProjectReference Include="..\KbStore.Catalog\KbStore.Catalog.csproj" />
    <ProjectReference Include="..\KbStore.Tests\KbStore.Tests.csproj" />
  </ItemGroup>

</Project>
