// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KbStoreApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InventoryModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The createdOn property</summary>
        public DateTimeOffset? CreatedOn { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The inventoryId property</summary>
        public Guid? InventoryId { get; set; }
        /// <summary>The partNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PartNumber { get; set; }
#nullable restore
#else
        public string PartNumber { get; set; }
#endif
        /// <summary>The status property</summary>
        public int? Status { get; set; }
        /// <summary>The stockQuantity property</summary>
        public int? StockQuantity { get; set; }
        /// <summary>The updatedOn property</summary>
        public DateTimeOffset? UpdatedOn { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::KbStoreApiClient.Models.InventoryModel"/> and sets the default values.
        /// </summary>
        public InventoryModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KbStoreApiClient.Models.InventoryModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KbStoreApiClient.Models.InventoryModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::KbStoreApiClient.Models.InventoryModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdOn", n => { CreatedOn = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "inventoryId", n => { InventoryId = n.GetGuidValue(); } },
                { "partNumber", n => { PartNumber = n.GetStringValue(); } },
                { "status", n => { Status = n.GetIntValue(); } },
                { "stockQuantity", n => { StockQuantity = n.GetIntValue(); } },
                { "updatedOn", n => { UpdatedOn = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdOn", CreatedOn);
            writer.WriteStringValue("description", Description);
            writer.WriteGuidValue("inventoryId", InventoryId);
            writer.WriteStringValue("partNumber", PartNumber);
            writer.WriteIntValue("status", Status);
            writer.WriteIntValue("stockQuantity", StockQuantity);
            writer.WriteDateTimeOffsetValue("updatedOn", UpdatedOn);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
