// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KbStoreApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaginatedResponseOfInventoryModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The page property</summary>
        public int? Page { get; set; }
        /// <summary>The results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KbStoreApiClient.Models.InventoryModel>? Results { get; set; }
#nullable restore
#else
        public List<global::KbStoreApiClient.Models.InventoryModel> Results { get; set; }
#endif
        /// <summary>The size property</summary>
        public int? Size { get; set; }
        /// <summary>The totalItems property</summary>
        public int? TotalItems { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::KbStoreApiClient.Models.PaginatedResponseOfInventoryModel"/> and sets the default values.
        /// </summary>
        public PaginatedResponseOfInventoryModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KbStoreApiClient.Models.PaginatedResponseOfInventoryModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KbStoreApiClient.Models.PaginatedResponseOfInventoryModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::KbStoreApiClient.Models.PaginatedResponseOfInventoryModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "page", n => { Page = n.GetIntValue(); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::KbStoreApiClient.Models.InventoryModel>(global::KbStoreApiClient.Models.InventoryModel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "size", n => { Size = n.GetIntValue(); } },
                { "totalItems", n => { TotalItems = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("page", Page);
            writer.WriteCollectionOfObjectValues<global::KbStoreApiClient.Models.InventoryModel>("results", Results);
            writer.WriteIntValue("size", Size);
            writer.WriteIntValue("totalItems", TotalItems);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
