// <auto-generated/>
#pragma warning disable CS0618
using KbStoreClient.StockItems.Item.Quantity.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace KbStoreClient.StockItems.Item.Quantity
{
    /// <summary>
    /// Builds and executes requests for operations under \stock-items\{id}\quantity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QuantityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KbStoreClient.stockItems.item.quantity.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::KbStoreClient.StockItems.Item.Quantity.Item.WithQuantityItemRequestBuilder"/></returns>
        public global::KbStoreClient.StockItems.Item.Quantity.Item.WithQuantityItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("quantity", position);
                return new global::KbStoreClient.StockItems.Item.Quantity.Item.WithQuantityItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the KbStoreClient.stockItems.item.quantity.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::KbStoreClient.StockItems.Item.Quantity.Item.WithQuantityItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::KbStoreClient.StockItems.Item.Quantity.Item.WithQuantityItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("quantity", position);
                return new global::KbStoreClient.StockItems.Item.Quantity.Item.WithQuantityItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KbStoreClient.StockItems.Item.Quantity.QuantityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuantityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/stock-items/{id}/quantity", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KbStoreClient.StockItems.Item.Quantity.QuantityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuantityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/stock-items/{id}/quantity", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
