services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:9.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
    - target: 18888
      published: 18888
    restart: unless-stopped
  queue:
    container_name: "queue"
    image: "docker.io/library/rabbitmq:4.1-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "QoscRSZpGxmBmAyxua8K7K"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "queue"
    volumes:
    - "kbstore-apphost-070774ae0c-queue-data:/var/lib/rabbitmq"
    ports:
    - target: 5672
      published: 5672
    - target: 15672
      published: 15672
    restart: unless-stopped
  pgsql:
    container_name: "pgsql"
    image: "docker.io/library/postgres:17.5"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "bRQehGrv5U63IAmqXUZU1z"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "pgsql"
    volumes:
    - "kbstore-apphost-070774ae0c-pgsql-data:/var/lib/postgresql/data"
    ports:
    - target: 5432
      published: 5432
    restart: unless-stopped
  domain-catalog:
    container_name: "domain-catalog"
    image: "domain-catalog:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__queue: "amqp://guest:QoscRSZpGxmBmAyxua8K7K@queue:5672"
      ConnectionStrings__inventory: "Host=pgsql;Port=5432;Username=postgres;Password=bRQehGrv5U63IAmqXUZU1z;Database=inventory"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "domain-catalog"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    restart: unless-stopped
  mongo:
    container_name: "mongo"
    image: "docker.io/library/mongo:8.0"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "c6l!isNmd87DQzI1WD63X5"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "mongo"
    volumes:
    - "kbstore-apphost-070774ae0c-mongo-data:/data/db"
    ports:
    - target: 27017
      published: 27017
    restart: unless-stopped
  domain-storefront:
    container_name: "domain-storefront"
    image: "domain-storefront:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ConnectionStrings__queue: "amqp://guest:QoscRSZpGxmBmAyxua8K7K@queue:5672"
      ConnectionStrings__storefront: "mongodb://admin:c6l!isNmd87DQzI1WD63X5@mongo:27017/storefront?authSource=admin&authMechanism=SCRAM-SHA-256"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "domain-storefront"
    restart: unless-stopped
  api:
    container_name: "api"
    image: "api:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      HTTP_PORTS: "8080"
      ConnectionStrings__queue: "amqp://guest:QoscRSZpGxmBmAyxua8K7K@queue:5672"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "api"
    ports:
    - target: 8080
      published: 10002
    - target: 8443
      published: 10003
    restart: unless-stopped
volumes:
  kbstore-apphost-070774ae0c-queue-data: {}
  kbstore-apphost-070774ae0c-pgsql-data: {}
  kbstore-apphost-070774ae0c-mongo-data: {}
